# Generated by Django 5.0.6 on 2024-06-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_broadwaystudent_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=30, null=True, verbose_name='Class name')),
                ('section', models.CharField(max_length=20, verbose_name='Class section')),
            ],
        ),
    ]
