# Generated by Django 5.0.6 on 2024-06-18 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_studentclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadwaystudent',
            name='student_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.studentclass'),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='class_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='class_type',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='class type'),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='ended',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='started_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentclass',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='Class name'),
        ),
        migrations.AlterField(
            model_name='studentclass',
            name='section',
            field=models.CharField(max_length=40, verbose_name='class Section'),
        ),
    ]
