# Generated by Django 5.0.6 on 2024-06-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_broadwaystudent_student_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclass',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='studentclass/'),
        ),
    ]
